name: Linux Windows

on:
  push:
    branches:
      - "master"
      - "continuous-integration"
      - "cross-platform"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"
      - "continuous-integration"

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR: ${{ github.workspace }}
  ARTIFACT: qt-planets-build.zip

jobs:
  build:
    runs-on: windows-2021

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Workspace
        run: |
          echo '${{ github.workspace }}'
          echo '${{ runner.temp }}'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2019_64"
          dir: ${{ runner.temp }}
          install-deps: "true"
          modules: 'qtcharts'

      - name: Create build directory
        run: mkdir -p ${{ env.SOURCE_DIR }}\build

      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}\build
        run: |
          qmake -r ${{ env.SOURCE_DIR }}\QtWidgetOpenGl.pro
          make

      - name: (9) Zip build
        working-directory: ${{ env.SOURCE_DIR  }}
        run: |
          7z a qt-planets-build.zip ${{ env.SOURCE_DIR  }}\build\* -r
          ls .
              
      - name: (10) Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.SOURCE_DIR  }}\${{ env.ARTIFACT }}