name: Linux Windows

on:
  push:
    branches:
      - "master"
      - "continuous-integration"
      - "cross-platform"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"
      - "continuous-integration"

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR: ${{ github.workspace }}
  ARTIFACT: qt-planets-build.zip
  QT_VERSION: 5.15.2

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Workspace
        run: |
          echo '${{ github.workspace }}'
          echo '${{ runner.temp }}'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2019_64"
          dir: ${{ runner.temp }}
          install-deps: "true"
          modules: "qtcharts"
      
      - name: (7) Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Create build directory
        run: mkdir ${{ env.SOURCE_DIR }}\build

      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}\build
        run: |
          qmake -r ${{ env.SOURCE_DIR }}\QtWidgetOpenGl.pro
          nmake

      - name: (9) Zip build
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          7z a qt-planets-build.zip ${{ env.SOURCE_DIR }}/build/* -r
          ls .

      - name: (10) Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.SOURCE_DIR }}/${{ env.ARTIFACT }}
