name: Build and Release Qt App (Windows)

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "5.15.2" # Specify the Qt version you need

      - name: Install dependencies
        run: |
          # Install any additional dependencies required for your app
          # For example, if you are using qmake, add the following line:
          QT += charts

      - name: Build
        run: |
          # Build your Qt application
          qmake
          make

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MyApp
          path: path/to/your/built/app

  release:
    name: Create Release
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: MyApp
          path: path/to/your/built/app

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Release Assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: path/to/your/built/app
          asset_name: MyApp.exe
          asset_content_type: application/octet-stream
