name: Linux Release

on:
  push:
    branches:
      - "master"
      - "continuous-integration"
      - "cross-platform"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"
      - "continuous-integration"

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 5.15.2
  ARTIFACT: qt-planets-linux-build.AppImage

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Workspace
        run: |
          echo '${{ github.workspace }}'
          echo '${{ runner.temp }}'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "5.15.2"
          host: "linux"
          target: "desktop"
          dir: ${{ runner.temp }}
          install-deps: "true"
          modules: 'qtcharts'

      - name: Create build directory
        run: mkdir ${{ env.SOURCE_DIR }}/build

      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}/build
        run: |
          qmake -r ${{ env.SOURCE_DIR }}/QtWidgetOpenGl.pro
          make

      - name: (9) Zip build
        working-directory: ${{ runner.temp }}
        run:  |
              7z a qt-planets-build.zip ${{ runner.temp }}\build\* -r
              
      - name: (10) Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\${{ env.ARTIFACT }}
